### ISSUE TITLE
Catalina is suspicious of you!

### ISSUE THREAD

**Issue by Kamiar17** [mattDavo/Yippy#14]
![Screen Shot 2020-10-14 at 13 04 22](https://user-images.githubusercontent.com/72865929/95982719-bf877500-0e20-11eb-9488-31844a8e3f53.png)
("Yippy.app" can't be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information.")
What can I do?

Many thanks.

**Comment by mattDavo** [comment]
Hey @Kamiar17, yeah this is because Yippy doesn't have a certified Apple certificate, so Catalina is suspicious of it! From memory, I don't think it can be certified as it breaches rules of the App Store that allow it to copy.

I can't remember if it's control or option, but try holding one of them down when you open Yippy, that should give you the option to open it anyway.

Let me know how you go. Cheers 😄

**Comment by mattDavo** [comment]
This is now stale. Closing.

**Comment by mickeyperlstein** [comment]
its back
“Yippy” can’t be opened because Apple cannot check it for malicious software.
version 2.8.1
mac os: BigSur 11.4

**Comment by mattDavo** [comment]
Hi @mickeyperlstein, this was never resolved. It is because the app is not notarized and doing so requires paying for a developer account. I have no other need for a developer account, so I will not be paying for one at this time.

**Comment by mickeyperlstein** [comment]
ok anyway for others, you can open a "suspicious app":

Click on System Preferences on your Mac Dock.
Choose Security & Privacy.
Tap the lock at the bottom left of the screen.
Enter your password to unlock Security and Privacy.
Choose the Anywhere under Allow apps downloaded from. ...
Click the unlocked lock to keep the change.
