### ISSUE TITLE
Deduplication for items

### ISSUE THREAD

**Issue by justbilt** [mattDavo/Yippy#8]
![image](https://user-images.githubusercontent.com/3746991/76706016-52dbb900-671f-11ea-8c57-8824da275fe1.png)

![image](https://user-images.githubusercontent.com/3746991/76705998-3d668f00-671f-11ea-82dd-ffb2f184ac62.png)

It would be great if you could deduplication the copied items.

**Comment by karlhorky** [comment]
Some keywords for search: duplicate, deduplicate, duplication

**Comment by mattDavo** [comment]
Resolved in https://github.com/mattDavo/Yippy/releases/tag/2.7.0. For now I have done this without any setting to restore the original behaviour. If that is required please raise a new issue.

This should also solve the problem for all types of pasteboard items but could cause some issues due to bad pasteboard data types. If there are any problems please raise a new issue.
